<a href="https://colab.research.google.com/github/pizu-commits/ARTIFICIAL-INTELLIGENCE/blob/main/NUMPY_LIBRARY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# *NUMPY LIBRARY*
it is library for computations
we can make 1D,2D,3D and more D array(require less time than pyhton list)

1D:[]

2D:[[]]

3D:[[[]]]


# **FUNTIONS:**
1.np.array(list) any data type and no commas

2.%timeit: tell the time of one line

3.%%time it:tell the time of whole code

(list function)4.arr.append() for wrtitng age se

5.arr.ndim#which dimention

6.np.zeros(no of zeros)

7.np.ones(no of zeros)

8.np.empty(no of emptiness)

9.np.arange(1,3)

10.np.eye(no of 1,one column elements)

11.np.linspace(1,4,num=5) range ko todo 5 numbers me

12.np.random.rand(4)

13.np.random.randn(2)(in negative also)

14.np.random.ranf(3) (float)

15.np.random.int(3)  for int(min,max,number)

16.linalg module(solve problems of the matrix)


insert(var,loc,nuber,axis)

delete(var,loc,axis)

append(add data )



WAYS FOR CREATING ARRAYS

In [7]:

import numpy as np
x=np.array(['komal','zahid'])
print(x)


['komal' 'zahid']


In [ ]:
%timeit [print("komal")]

In [ ]:
%%timeit #now all code

In [24]:
#list has append function
l=[]
for i in range (1,10):
 l.append(int(input("enter:")))
print(l)

enter:1
enter:2
enter:3
enter:4
enter:5
enter:6
enter:7
enter:8
enter:9
[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [25]:
l=np.array([[1,2,3,4],[5,6,7,8]])
print(l.ndim)

2


In [28]:
l=np.array([1,2,3,4],ndmin = 10)
print(l)

[[[[[[[[[[1 2 3 4]]]]]]]]]]


In [37]:
l1=np.zeros((3,3))
print(l1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [45]:
l2=np.ones(2)
print(l2)
l3=np.empty(2)
print(l3)
l4=np.arange(4,10)
print(l4)
l5=np.eye(4)
print(l5)
l5=np.random.randn(5)
print(l5)
l6=np.linspace(1,4,num=9)
print(l6)

[1. 1.]
[1. 1.]
[4 5 6 7 8 9]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[-0.42286236 -0.19296334  1.01501927 -0.65473412 -1.35908829]
[1.    1.375 1.75  2.125 2.5   2.875 3.25  3.625 4.   ]


In [50]:
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])
c=a+b
print(c)

[2 4 6 8]
